// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxoloxuebenfkmsvhpqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4b2xveHVlYmVuZmttc3ZocHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyODg3MDEsImV4cCI6MjA2Nzg2NDcwMX0.sNyuVu8tDGDcFpo1u7AoA9uu6Mp0QYdXNqWMKSPAqbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});